"""initial schema

Revision ID: a0db532d69b6
Revises: 
Create Date: 2026-07-08 23:03:53.081694
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a0db532d69b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_actions',
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('confirm', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id')
    )
    op.create_table('approval_items',
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('entity_label', sa.String(length=512), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=False),
    sa.Column('proposed_payload', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('final_value', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_items_entity_id'), 'approval_items', ['entity_id'], unique=False)
    op.create_index(op.f('ix_approval_items_entity_type'), 'approval_items', ['entity_type'], unique=False)
    op.create_index(op.f('ix_approval_items_status'), 'approval_items', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('business_metrics',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('table_qualified_name', sa.String(length=512), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('aggregation', sa.String(length=32), nullable=True),
    sa.Column('is_kpi', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_metrics_name'), 'business_metrics', ['name'], unique=True)
    op.create_table('catalog_databases',
    sa.Column('connector_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_databases_connector_id'), 'catalog_databases', ['connector_id'], unique=False)
    op.create_index(op.f('ix_catalog_databases_name'), 'catalog_databases', ['name'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('connector_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('config_overrides',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_overrides_key'), 'config_overrides', ['key'], unique=True)
    op.create_table('dashboards',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('refresh_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_dashboards_user_id'), 'dashboards', ['user_id'], unique=False)
    op.create_table('execution_history',
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('connector_id', sa.String(length=64), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('refined_prompt', sa.Text(), nullable=True),
    sa.Column('intent', sa.JSON(), nullable=True),
    sa.Column('execution_plan', sa.JSON(), nullable=True),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('optimized_sql', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('tables_used', sa.JSON(), nullable=True),
    sa.Column('reused_query_id', sa.String(length=32), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_history_session_id'), 'execution_history', ['session_id'], unique=False)
    op.create_table('glossary_terms',
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('business_meaning', sa.Text(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_terms_term'), 'glossary_terms', ['term'], unique=True)
    op.create_table('metadata_versions',
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('change_source', sa.String(length=32), nullable=False),
    sa.Column('approval_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_versions_entity_id'), 'metadata_versions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_metadata_versions_entity_type'), 'metadata_versions', ['entity_type'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_name'), 'prompt_templates', ['name'], unique=False)
    op.create_table('query_library',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('normalized_question', sa.Text(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('connector_id', sa.String(length=64), nullable=True),
    sa.Column('tables_used', sa.JSON(), nullable=True),
    sa.Column('intent', sa.JSON(), nullable=True),
    sa.Column('execution_plan', sa.JSON(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('positive_feedback', sa.Integer(), nullable=False),
    sa.Column('negative_feedback', sa.Integer(), nullable=False),
    sa.Column('avg_execution_ms', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_library_question'), 'query_library', ['question'], unique=False)
    op.create_table('saved_queries',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('connector_id', sa.String(length=64), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_queries_user_id'), 'saved_queries', ['user_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('connector_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tables_synced', sa.Integer(), nullable=False),
    sa.Column('columns_synced', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_connector_id'), 'sync_runs', ['connector_id'], unique=False)
    op.create_table('catalog_tables',
    sa.Column('database_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('table_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technical_comment', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('steward', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_format', sa.String(length=64), nullable=True),
    sa.Column('compression', sa.String(length=64), nullable=True),
    sa.Column('partition_columns', sa.JSON(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['catalog_databases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_tables_database_id'), 'catalog_tables', ['database_id'], unique=False)
    op.create_index(op.f('ix_catalog_tables_name'), 'catalog_tables', ['name'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('execution_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_history.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('dashboard_widgets',
    sa.Column('dashboard_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('widget_type', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=16), nullable=False),
    sa.Column('sql', sa.Text(), nullable=True),
    sa.Column('connector_id', sa.String(length=64), nullable=True),
    sa.Column('visualization', sa.JSON(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('source_execution_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_widgets_dashboard_id'), 'dashboard_widgets', ['dashboard_id'], unique=False)
    op.create_table('feedback',
    sa.Column('execution_id', sa.String(length=32), nullable=True),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('corrected_sql', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('learning', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_execution_id'), 'feedback', ['execution_id'], unique=False)
    op.create_table('synonyms',
    sa.Column('term_id', sa.String(length=32), nullable=False),
    sa.Column('synonym', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['glossary_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synonyms_synonym'), 'synonyms', ['synonym'], unique=False)
    op.create_index(op.f('ix_synonyms_term_id'), 'synonyms', ['term_id'], unique=False)
    op.create_table('catalog_columns',
    sa.Column('table_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=128), nullable=False),
    sa.Column('inferred_semantic_type', sa.String(length=64), nullable=True),
    sa.Column('semantic_confidence', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technical_comment', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('classification', sa.String(length=64), nullable=True),
    sa.Column('is_pii', sa.Boolean(), nullable=False),
    sa.Column('is_partition', sa.Boolean(), nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('null_percentage', sa.Float(), nullable=True),
    sa.Column('distinct_percentage', sa.Float(), nullable=True),
    sa.Column('distinct_count', sa.Integer(), nullable=True),
    sa.Column('min_value', sa.String(length=255), nullable=True),
    sa.Column('max_value', sa.String(length=255), nullable=True),
    sa.Column('sample_values', sa.JSON(), nullable=True),
    sa.Column('top_values', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['catalog_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_columns_name'), 'catalog_columns', ['name'], unique=False)
    op.create_index(op.f('ix_catalog_columns_table_id'), 'catalog_columns', ['table_id'], unique=False)
    op.create_table('catalog_relationships',
    sa.Column('from_table_id', sa.String(length=32), nullable=False),
    sa.Column('from_column', sa.String(length=255), nullable=False),
    sa.Column('to_table_id', sa.String(length=32), nullable=False),
    sa.Column('to_column', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_table_id'], ['catalog_tables.id'], ),
    sa.ForeignKeyConstraint(['to_table_id'], ['catalog_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_relationships_from_table_id'), 'catalog_relationships', ['from_table_id'], unique=False)
    op.create_index(op.f('ix_catalog_relationships_to_table_id'), 'catalog_relationships', ['to_table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_relationships_to_table_id'), table_name='catalog_relationships')
    op.drop_index(op.f('ix_catalog_relationships_from_table_id'), table_name='catalog_relationships')
    op.drop_table('catalog_relationships')
    op.drop_index(op.f('ix_catalog_columns_table_id'), table_name='catalog_columns')
    op.drop_index(op.f('ix_catalog_columns_name'), table_name='catalog_columns')
    op.drop_table('catalog_columns')
    op.drop_index(op.f('ix_synonyms_term_id'), table_name='synonyms')
    op.drop_index(op.f('ix_synonyms_synonym'), table_name='synonyms')
    op.drop_table('synonyms')
    op.drop_index(op.f('ix_feedback_execution_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_dashboard_widgets_dashboard_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_catalog_tables_name'), table_name='catalog_tables')
    op.drop_index(op.f('ix_catalog_tables_database_id'), table_name='catalog_tables')
    op.drop_table('catalog_tables')
    op.drop_index(op.f('ix_sync_runs_connector_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_saved_queries_user_id'), table_name='saved_queries')
    op.drop_table('saved_queries')
    op.drop_index(op.f('ix_query_library_question'), table_name='query_library')
    op.drop_table('query_library')
    op.drop_index(op.f('ix_prompt_templates_name'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_metadata_versions_entity_type'), table_name='metadata_versions')
    op.drop_index(op.f('ix_metadata_versions_entity_id'), table_name='metadata_versions')
    op.drop_table('metadata_versions')
    op.drop_index(op.f('ix_glossary_terms_term'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    op.drop_index(op.f('ix_execution_history_session_id'), table_name='execution_history')
    op.drop_table('execution_history')
    op.drop_index(op.f('ix_dashboards_user_id'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_config_overrides_key'), table_name='config_overrides')
    op.drop_table('config_overrides')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_catalog_databases_name'), table_name='catalog_databases')
    op.drop_index(op.f('ix_catalog_databases_connector_id'), table_name='catalog_databases')
    op.drop_table('catalog_databases')
    op.drop_index(op.f('ix_business_metrics_name'), table_name='business_metrics')
    op.drop_table('business_metrics')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approval_items_status'), table_name='approval_items')
    op.drop_index(op.f('ix_approval_items_entity_type'), table_name='approval_items')
    op.drop_index(op.f('ix_approval_items_entity_id'), table_name='approval_items')
    op.drop_table('approval_items')
    op.drop_table('api_actions')
    # ### end Alembic commands ###
